version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mindful_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mindful
    volumes:
      - mindful_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    container_name: mindful_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "11500:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  mindful_pgdata: