"""add like/dislike columns

Revision ID: 3fe69973c35a
Revises: f27d89c1c1fa
Create Date: 2025-12-03 23:23:02.453276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe69973c35a'
down_revision: Union[str, None] = 'f27d89c1c1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('like', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('dislike', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'dislike')
    op.drop_column('chat_messages', 'like')
    # ### end Alembic commands ###
