"""Change all created_at default time format to local timezone

Revision ID: 79544c0459fa
Revises: b5cb4b2fac9a
Create Date: 2025-03-21 22:10:38.236132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79544c0459fa"
down_revision: Union[str, None] = "b5cb4b2fac9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
