"""Create Big Five Traits Model

Revision ID: 8c2e868684c7
Revises: 79544c0459fa
Create Date: 2025-03-22 14:21:42.136549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c2e868684c7"
down_revision: Union[str, None] = "79544c0459fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "big_five_traits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("big_five_data", sa.JSON(), nullable=False),
        sa.Column("max_value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_big_five_traits_id"), "big_five_traits", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_big_five_traits_id"), table_name="big_five_traits")
    op.drop_table("big_five_traits")
    # ### end Alembic commands ###
