"""Create behavior table

Revision ID: e90b72ee2de0
Revises: 29605435e345
Create Date: 2025-03-14 22:54:02.313619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e90b72ee2de0"
down_revision: Union[str, None] = "29605435e345"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_behaviors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("behavior_id", sa.String(), nullable=True),
        sa.Column("behavior_title", sa.String(), nullable=True),
        sa.Column("first_priority", sa.Boolean(), nullable=True),
        sa.Column("high_priority", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_behaviors_id"), "user_behaviors", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_behaviors_id"), table_name="user_behaviors")
    op.drop_table("user_behaviors")
    # ### end Alembic commands ###
