"""remove relation with user for big five traits

Revision ID: f27d89c1c1fa
Revises: 8c2e868684c7
Create Date: 2025-03-22 14:59:23.609788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f27d89c1c1fa"
down_revision: Union[str, None] = "8c2e868684c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
